version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: lodash
    versions:
    - 4.17.20
